"""add admin flag to users

Revision ID: 7e1bef9a4213
Revises: f471ed435c79
Create Date: 2023-08-16 08:52:48.532981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e1bef9a4213"
down_revision: Union[str, None] = "f471ed435c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("admin", sa.Boolean(), nullable=False, default=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("admin")

    # ### end Alembic commands ###
