"""add index on is_open

Revision ID: 04c1db076a73
Revises: b8ea9a2053ba
Create Date: 2023-08-23 11:51:23.869372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04c1db076a73"
down_revision: Union[str, None] = "b8ea9a2053ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auctiongroup", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auctiongroup_is_open"), ["is_open"], unique=False)

    with op.batch_alter_table("auctionlot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auctionlot_is_open"), ["is_open"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auctionlot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auctionlot_is_open"))

    with op.batch_alter_table("auctiongroup", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auctiongroup_is_open"))

    # ### end Alembic commands ###
