"""add notification type for each filter

Revision ID: 0ff295211ebf
Revises: 80d38c9c852a
Create Date: 2023-08-09 23:24:09.956429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ff295211ebf"
down_revision: Union[str, None] = "80d38c9c852a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filter", sa.Column("notification_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filter", "notification_type")
    # ### end Alembic commands ###
