"""default status, exceeded item limit meta on notification table

Revision ID: ae7f29834e2b
Revises: 196123f7ddc9
Create Date: 2023-08-24 23:08:49.218432

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae7f29834e2b"
down_revision: Union[str, None] = "196123f7ddc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exceeded_item_limit", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("exceeded_item_limit")

    # ### end Alembic commands ###
