"""remove problematic index on ag, add indexes on more al properties

Revision ID: 196123f7ddc9
Revises: 04c1db076a73
Create Date: 2023-08-24 11:04:24.723895

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "196123f7ddc9"
down_revision: Union[str, None] = "04c1db076a73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auctiongroup", schema=None) as batch_op:
        batch_op.drop_index("ix_auctiongroup_is_open")

    with op.batch_alter_table("auctionlot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auctionlot_closed_date"), ["closed_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auctionlot_winning_bid_amount"), ["winning_bid_amount"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "admin", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "admin",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("auctionlot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auctionlot_winning_bid_amount"))
        batch_op.drop_index(batch_op.f("ix_auctionlot_closed_date"))

    with op.batch_alter_table("auctiongroup", schema=None) as batch_op:
        batch_op.create_index("ix_auctiongroup_is_open", ["is_open"], unique=False)

    # ### end Alembic commands ###
